# Server
server.port=8088

# Freemarker
spring.freemarker.template-loader-path=classpath:/templates
spring.freemarker.suffix=.ftl
spring.freemarker.cache=false
spring.freemarker.enabled=true
spring.freemarker.content-type=text/html
spring.freemarker.charset=UTF-8

# Database
spring.datasource.url=jdbc:h2:mem:employees_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Log SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
logging.level.org.hibernate.SQL=DEBUG
# log parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
