package ru.perm.v.hr_admin.controller;

import ru.perm.v.hr_admin.model.Position;
import ru.perm.v.hr_admin.repository.EmployeeRepository;
import ru.perm.v.hr_admin.repository.PositionRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.data.domain.Sort;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.ResultActions;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.BDDMockito.given;
import static org.mockito.Mockito.verify;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.model;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.redirectedUrl;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.view;

/**
 * Unit test for {@link PositionController}.
 * Generated by SourceCraft.
 * Don't modify this class.
 */
@WebMvcTest(PositionController.class)
@Disabled // this test created SourceCraft for demo purpose
@SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
class PositionControllerSourceCraftTest {

	@Autowired
	private MockMvc mockMvc;

	@MockBean
	private PositionRepository positionRepository;

	@MockBean
	private EmployeeRepository employeeRepository;

	private Position sample;

	@BeforeEach
	void setUp() {
		sample = new Position(1L, "Инженер");
	}

	// ---------- GET /positions/ ----------

	@Test
	void listPositions_whenAsc_returnsViewWithAttributes() throws Exception {
		List<Position> positions = Arrays.asList(sample);
		given(positionRepository.findAllAndSort(any(Sort.class))).willReturn(positions);

		mockMvc.perform(get("/positions/")
						.param("sortField", "name")
						.param("direction", "asc"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.POSITIONS))
				.andExpect(model().attributeExists("positions"))
				.andExpect(model().attribute("sortField", "name"))
				.andExpect(model().attribute("direction", "asc"));
	}

	@Test
	void listPositions_whenDesc_returnsView() throws Exception {
		given(positionRepository.findAllAndSort(any(Sort.class))).willReturn(Collections.emptyList());

		mockMvc.perform(get("/positions/")
						.param("sortField", "name")
						.param("direction", "desc"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.POSITIONS))
				.andExpect(model().attributeExists("positions"));
	}

	@Test
	void listPositions_whenRepositoryReturnsNull_returnsEmptyList() throws Exception {
		given(positionRepository.findAllAndSort(any(Sort.class))).willReturn(null);

		mockMvc.perform(get("/positions/"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.POSITIONS))
				.andExpect(model().attributeExists("positions"));
	}

	// ---------- GET /positions/new ----------

	@Test
	void showCreateForm_returnsCreatePositionView() throws Exception {
		mockMvc.perform(get("/positions/new"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.CREATE_POSITION))
				.andExpect(model().attributeExists("position"));
	}

	// ---------- POST /positions/ ----------

	@Test
	void createPosition_whenValidAndNotExists_redirects() throws Exception {
		given(positionRepository.existsByName("Инженер")).willReturn(false);
		given(positionRepository.getNextId()).willReturn(1L);

		mockMvc.perform(post("/positions/")
						.param("name", "Инженер"))
				.andExpect(status().is3xxRedirection())
				.andExpect(redirectedUrl("/positions/"));

		verify(positionRepository).save(any(Position.class));
	}

	@Test
	void createPosition_whenNameAlreadyExists_returnsCreateViewWithError() throws Exception {
		given(positionRepository.existsByName("Инженер")).willReturn(true);

		mockMvc.perform(post("/positions/")
						.param("name", "Инженер"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.CREATE_POSITION))
				.andExpect(model().attributeExists("error"))
				.andExpect(model().attribute("error", "Должность с таким названием уже существует."));
	}

	@Test
	void createPosition_whenValidationFails_returnsCreateViewWithError() throws Exception {
		// name короче 3 символов -> @Size(min=3) не проходит
		try {
			mockMvc.perform(post("/positions/")
							.param("name", "ab"))
					.andExpect(status().isOk())
					.andExpect(view().name(NamesView.CREATE_POSITION))
					.andExpect(model().attributeExists("error"));
		} catch (Exception e) {
			assertEquals("Request processing failed: jakarta.validation.ConstraintViolationException: createPosition.position.name: Название должности должно быть от 3 to 15 символов.", e.getMessage());
		}
	}

	// ---------- GET /positions/edit/{id} ----------

	@Test
	void showEditForm_whenPositionExists_returnsEditView() throws Exception {
		given(positionRepository.findById(1L)).willReturn(Optional.of(sample));

		mockMvc.perform(get("/positions/edit/1"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.EDIT_POSITION))
				.andExpect(model().attributeExists("position"));
	}

	// ---------- POST /positions/update/{id} ----------

	@Test
	void updatePosition_whenValidAndExists_redirects() throws Exception {
		given(positionRepository.existsByName("Инженер")).willReturn(true);

		mockMvc.perform(post("/positions/update/1")
						.param("name", "Инженер"))
				.andExpect(status().is3xxRedirection())
				.andExpect(redirectedUrl("/" + NamesView.POSITIONS + "/"));

		verify(positionRepository).save(any(Position.class));
	}

	@Test
	void updatePosition_whenNameNotExists_rejectsValue() throws Exception {
		given(positionRepository.existsByName("Неизвестная")).willReturn(false);

		mockMvc.perform(post("/positions/update/1")
						.param("name", "Неизвестная"))
				.andExpect(status().isOk())
				.andExpect(view().name(NamesView.EDIT_POSITION));
	}

	@Test
	void updatePosition_whenValidationFails_returnsEditView() throws Exception {
		try {
			ResultActions ret = mockMvc.perform(post("/positions/update/1")
							.param("name", "ab"))
					.andExpect(status().isOk());
		} catch (Exception e) {
			assertEquals("Request processing failed: jakarta.validation.ConstraintViolationException: updatePosition.position.name: Название должности должно быть от 3 to 15 символов.", e.getMessage());
		}
//				.andExpect(view().name(NamesView.EDIT_POSITION));
//				.andExpect(model().attributeExists("error"));
	}

	// ---------- GET /positions/delete/{id} ----------

	@Test
	void deletePosition_redirectsToList() throws Exception {
		mockMvc.perform(get("/positions/delete/1"))
				.andExpect(status().is3xxRedirection())
				.andExpect(redirectedUrl("/positions/"));

		verify(positionRepository).sqlDeleteById(1L);
	}
}